[CLOUDOPS-548] Allow retry on openstack HttpException
vexxhost/staffeln pull request #127
Opened 2024-10-25 08:51 UTC by ricolin

2025-01-15 03:45 UTC, mnaser requested changes

2025-01-15 03:45 UTC, mnaser commented on staffeln/conf/conductor.py
> +    cfg.StrOpt(
Should we use ListOpt here?

2025-01-15 03:45 UTC, mnaser commented on staffeln/conf/conductor.py
> +            "exception. Default only `404` is skipped."
this will be list opt so no need to be csv.

2025-01-15 03:45 UTC, mnaser commented on staffeln/common/openstack.py
> +            skip_codes = CONF.openstack.skip_retry_codes.replace(" ", "").split(",")
This would have to be revised.

2025-01-15 03:45 UTC, mnaser commented on staffeln/conductor/backup.py
Can we drop the changes in this PR for this?

2025-01-15 03:45 UTC, mnaser commented on tox.ini
> +envlist = py3,py38,py39,py310,linters
I think this is not necesary for this change.

2025-01-15 03:45 UTC, mnaser commented on tox.ini
> +       -r{toxinidir}/test-requirements.txt
I think this is not necessary for this change thier.

2025-01-23 02:38 UTC, ricolin commented on tox.ini
> +       -r{toxinidir}/test-requirements.txt
we need tenacity and openstack modules in py3 test

2025-02-17 16:32 UTC, mnaser approved these changes

2025-02-17 16:32 UTC, merged